import { Commodity, CommodityCategory, PreciousMetalsSubcategory, EnergySubcategory, IndustrialMetalsSubcategory, AgriculturalSubcategory } from '@/types';

/**
 * Mock commodity data for development
 */
export const MOCK_COMMODITIES: Commodity[] = [
    // Precious Metals - Core (핵심 귀금속)
    {
        id: '1',
        symbol: 'XAUUSD',
        name: 'Gold',
        nameKo: '금',
        category: CommodityCategory.PRECIOUS_METALS,
        subcategory: PreciousMetalsSubcategory.CORE,
        currentPrice: 4532.20,
        currency: 'USD',
        change: 45.30,
        changePercent: 1.01,
        lastUpdated: new Date(),
        icon: '🥇',
    },
    {
        id: '2',
        symbol: 'XAGUSD',
        name: 'Silver',
        nameKo: '은',
        category: CommodityCategory.PRECIOUS_METALS,
        subcategory: PreciousMetalsSubcategory.CORE,
        currentPrice: 79.11,
        currency: 'USD',
        change: 1.25,
        changePercent: 1.60,
        lastUpdated: new Date(),
        icon: '🥈',
    },
    {
        id: '3',
        symbol: 'XPTUSD',
        name: 'Platinum',
        nameKo: '백금',
        category: CommodityCategory.PRECIOUS_METALS,
        subcategory: PreciousMetalsSubcategory.PGM_SPECIALTY,
        currentPrice: 1150.00,
        currency: 'USD',
        change: 15.50,
        changePercent: 1.35,
        lastUpdated: new Date(),
        icon: '⚪',
    },
    // Energy - Crude Oil (원유)
    {
        id: '4',
        symbol: 'CL=F',
        name: 'Crude Oil WTI',
        nameKo: 'WTI 원유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 56.74,
        currency: 'USD',
        change: -0.85,
        changePercent: -1.48,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    {
        id: '5',
        symbol: 'BZ=F',
        name: 'Brent Crude',
        nameKo: '브렌트유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 60.50,
        currency: 'USD',
        change: -0.90,
        changePercent: -1.45,
        lastUpdated: new Date(),
        icon: '⛽',
    },
    {
        id: '6',
        symbol: 'DUBAI',
        name: 'Dubai',
        nameKo: '두바이유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 58.20,
        currency: 'USD',
        change: -0.75,
        changePercent: -1.27,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    {
        id: '7',
        symbol: 'OMAN',
        name: 'Oman',
        nameKo: '오만유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 58.80,
        currency: 'USD',
        change: -0.80,
        changePercent: -1.34,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    {
        id: '8',
        symbol: 'MURBAN',
        name: 'Murban',
        nameKo: '무르반유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 59.10,
        currency: 'USD',
        change: -0.85,
        changePercent: -1.42,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    {
        id: '9',
        symbol: 'TAPIS',
        name: 'Tapis',
        nameKo: '타피스유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 62.30,
        currency: 'USD',
        change: -0.95,
        changePercent: -1.50,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    {
        id: '10',
        symbol: 'BONNY',
        name: 'Bonny Light',
        nameKo: '보니라이트유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 61.50,
        currency: 'USD',
        change: -0.88,
        changePercent: -1.41,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    {
        id: '11',
        symbol: 'LSC',
        name: 'Light Sweet Crude',
        nameKo: '경질 저유황 원유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 57.20,
        currency: 'USD',
        change: -0.82,
        changePercent: -1.41,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    {
        id: '12',
        symbol: 'HEAVY',
        name: 'Heavy Crude',
        nameKo: '중질유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 52.30,
        currency: 'USD',
        change: -0.70,
        changePercent: -1.32,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    {
        id: '13',
        symbol: 'SOUR',
        name: 'Sour Crude',
        nameKo: '고유황 원유',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.CRUDE_OIL,
        currentPrice: 54.10,
        currency: 'USD',
        change: -0.75,
        changePercent: -1.37,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    // Energy - Gas (가스 에너지)
    {
        id: '14',
        symbol: 'NG=F',
        name: 'Natural Gas',
        nameKo: '천연가스',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 3.85,
        currency: 'USD',
        change: 0.12,
        changePercent: 3.22,
        lastUpdated: new Date(),
        icon: '🔥',
    },
    {
        id: '15',
        symbol: 'HH',
        name: 'Henry Hub',
        nameKo: '헨리허브 천연가스',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 3.92,
        currency: 'USD',
        change: 0.15,
        changePercent: 3.98,
        lastUpdated: new Date(),
        icon: '🔥',
    },
    {
        id: '16',
        symbol: 'TTF',
        name: 'TTF (Title Transfer Facility)',
        nameKo: '유럽 TTF 가스',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 45.50,
        currency: 'USD',
        change: 1.85,
        changePercent: 4.24,
        lastUpdated: new Date(),
        icon: '🔥',
    },
    {
        id: '17',
        symbol: 'NBP',
        name: 'NBP (National Balancing Point)',
        nameKo: '영국 NBP 가스',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 44.20,
        currency: 'USD',
        change: 1.75,
        changePercent: 4.12,
        lastUpdated: new Date(),
        icon: '🔥',
    },
    {
        id: '18',
        symbol: 'LNG',
        name: 'LNG',
        nameKo: '액화천연가스',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 18.50,
        currency: 'USD',
        change: 0.85,
        changePercent: 4.82,
        lastUpdated: new Date(),
        icon: '❄️',
    },
    {
        id: '19',
        symbol: 'LNG_SPOT',
        name: 'LNG Spot',
        nameKo: 'LNG 현물',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 19.80,
        currency: 'USD',
        change: 0.95,
        changePercent: 5.04,
        lastUpdated: new Date(),
        icon: '❄️',
    },
    {
        id: '20',
        symbol: 'LNG_LT',
        name: 'LNG Long-term Contract',
        nameKo: 'LNG 장기계약 가격',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 16.20,
        currency: 'USD',
        change: 0.50,
        changePercent: 3.18,
        lastUpdated: new Date(),
        icon: '❄️',
    },
    {
        id: '21',
        symbol: 'JKM',
        name: 'JKM (Japan Korea Marker)',
        nameKo: 'JKM (한·일 LNG 기준가)',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 19.50,
        currency: 'USD',
        change: 0.88,
        changePercent: 4.73,
        lastUpdated: new Date(),
        icon: '❄️',
    },
    {
        id: '22',
        symbol: 'LPG',
        name: 'LPG',
        nameKo: '액화석유가스',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 625.00,
        currency: 'USD',
        change: 12.50,
        changePercent: 2.04,
        lastUpdated: new Date(),
        icon: '⛽',
    },
    {
        id: '23',
        symbol: 'PROPANE',
        name: 'Propane',
        nameKo: '프로판',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 0.85,
        currency: 'USD',
        change: 0.02,
        changePercent: 2.41,
        lastUpdated: new Date(),
        icon: '⛽',
    },
    {
        id: '24',
        symbol: 'BUTANE',
        name: 'Butane',
        nameKo: '부탄',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.GAS,
        currentPrice: 0.92,
        currency: 'USD',
        change: -0.03,
        changePercent: -3.16,
        lastUpdated: new Date(),
        icon: '⛽',
    },
    // Energy - Electricity (전력)
    {
        id: '25',
        symbol: 'ELEC',
        name: 'Electricity',
        nameKo: '전력',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.ELECTRICITY,
        currentPrice: 85.50,
        currency: 'USD',
        change: 3.25,
        changePercent: 3.95,
        lastUpdated: new Date(),
        icon: '⚡',
    },
    {
        id: '26',
        symbol: 'BASE_POWER',
        name: 'Base Load Power',
        nameKo: '기저부하 전력',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.ELECTRICITY,
        currentPrice: 75.25,
        currency: 'USD',
        change: 2.15,
        changePercent: 2.94,
        lastUpdated: new Date(),
        icon: '⚡',
    },
    {
        id: '27',
        symbol: 'PEAK_POWER',
        name: 'Peak Load Power',
        nameKo: '최대부하 전력',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.ELECTRICITY,
        currentPrice: 125.75,
        currency: 'USD',
        change: 5.50,
        changePercent: 4.57,
        lastUpdated: new Date(),
        icon: '⚡',
    },
    {
        id: '28',
        symbol: 'REGIONAL_POWER',
        name: 'Regional Power Prices',
        nameKo: '지역별 전력 가격',
        category: CommodityCategory.ENERGY,
        subcategory: EnergySubcategory.ELECTRICITY,
        currentPrice: 92.30,
        currency: 'USD',
        change: -1.85,
        changePercent: -1.96,
        lastUpdated: new Date(),
        icon: '⚡',
    },
    // Agriculture - Grains (곡물)
    {
        id: '29',
        symbol: 'ZC=F',
        name: 'Corn',
        nameKo: '옥수수',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.GRAINS,
        currentPrice: 485.25,
        currency: 'USD',
        change: 3.75,
        changePercent: 0.78,
        lastUpdated: new Date(),
        icon: '🌽',
    },
    {
        id: '30',
        symbol: 'ZW=F',
        name: 'Wheat',
        nameKo: '밀',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.GRAINS,
        currentPrice: 625.50,
        currency: 'USD',
        change: -8.25,
        changePercent: -1.30,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    {
        id: '31',
        symbol: 'ZO=F',
        name: 'Oats',
        nameKo: '오트',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.GRAINS,
        currentPrice: 385.75,
        currency: 'USD',
        change: 2.50,
        changePercent: 0.65,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    {
        id: '32',
        symbol: 'ZR=F',
        name: 'Rice',
        nameKo: '쌀',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.GRAINS,
        currentPrice: 16.75,
        currency: 'USD',
        change: 0.25,
        changePercent: 1.52,
        lastUpdated: new Date(),
        icon: '🍚',
    },
    {
        id: '33',
        symbol: 'BARLEY',
        name: 'Barley',
        nameKo: '보리',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.GRAINS,
        currentPrice: 245.30,
        currency: 'USD',
        change: -3.20,
        changePercent: -1.29,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    {
        id: '34',
        symbol: 'SORGHUM',
        name: 'Sorghum',
        nameKo: '수수',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.GRAINS,
        currentPrice: 425.60,
        currency: 'USD',
        change: 5.40,
        changePercent: 1.28,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    // Agriculture - Oilseeds & Oils (유지종자 및 유지)
    {
        id: '35',
        symbol: 'ZS=F',
        name: 'Soybeans',
        nameKo: '대두',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.OILSEEDS,
        currentPrice: 1425.50,
        currency: 'USD',
        change: -12.25,
        changePercent: -0.85,
        lastUpdated: new Date(),
        icon: '🫘',
    },
    {
        id: '36',
        symbol: 'ZM=F',
        name: 'Soybean Meal',
        nameKo: '대두박',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.OILSEEDS,
        currentPrice: 425.80,
        currency: 'USD',
        change: 8.30,
        changePercent: 1.99,
        lastUpdated: new Date(),
        icon: '🫘',
    },
    {
        id: '37',
        symbol: 'ZL=F',
        name: 'Soybean Oil',
        nameKo: '대두유',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.OILSEEDS,
        currentPrice: 52.45,
        currency: 'USD',
        change: -0.85,
        changePercent: -1.59,
        lastUpdated: new Date(),
        icon: '🫘',
    },
    {
        id: '38',
        symbol: 'RS=F',
        name: 'Canola',
        nameKo: '카놀라',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.OILSEEDS,
        currentPrice: 432.50,
        currency: 'USD',
        change: 9.25,
        changePercent: 2.18,
        lastUpdated: new Date(),
        icon: '🌻',
    },
    {
        id: '39',
        symbol: 'SUNFLOWER',
        name: 'Sunflower Seeds',
        nameKo: '해바라기씨',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.OILSEEDS,
        currentPrice: 625.00,
        currency: 'USD',
        change: -5.75,
        changePercent: -0.91,
        lastUpdated: new Date(),
        icon: '🌻',
    },
    {
        id: '40',
        symbol: 'PALM',
        name: 'Palm Oil',
        nameKo: '팜유',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.OILSEEDS,
        currentPrice: 950.00,
        currency: 'USD',
        change: 19.00,
        changePercent: 2.04,
        lastUpdated: new Date(),
        icon: '🌴',
    },
    // Agriculture - Soft Commodities (가공 식품/기호 농산물)
    {
        id: '41',
        symbol: 'KC=F',
        name: 'Coffee',
        nameKo: '커피',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SOFT_COMMODITIES,
        currentPrice: 185.40,
        currency: 'USD',
        change: 4.20,
        changePercent: 2.32,
        lastUpdated: new Date(),
        icon: '☕',
    },
    {
        id: '42',
        symbol: 'SB=F',
        name: 'Sugar',
        nameKo: '설탕',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SOFT_COMMODITIES,
        currentPrice: 24.35,
        currency: 'USD',
        change: 0.45,
        changePercent: 1.88,
        lastUpdated: new Date(),
        icon: '🍬',
    },
    {
        id: '43',
        symbol: 'CC=F',
        name: 'Cocoa',
        nameKo: '코코아',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SOFT_COMMODITIES,
        currentPrice: 4250.00,
        currency: 'USD',
        change: 85.00,
        changePercent: 2.04,
        lastUpdated: new Date(),
        icon: '🍫',
    },
    {
        id: '44',
        symbol: 'OJ=F',
        name: 'Orange Juice',
        nameKo: '오렌지 주스',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SOFT_COMMODITIES,
        currentPrice: 285.50,
        currency: 'USD',
        change: -5.25,
        changePercent: -1.81,
        lastUpdated: new Date(),
        icon: '🍊',
    },
    {
        id: '45',
        symbol: 'CT=F',
        name: 'Cotton',
        nameKo: '면화',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SOFT_COMMODITIES,
        currentPrice: 82.15,
        currency: 'USD',
        change: -1.20,
        changePercent: -1.44,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    // Agriculture - Livestock (축산물)
    {
        id: '46',
        symbol: 'LE=F',
        name: 'Live Cattle',
        nameKo: '생우',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.LIVESTOCK,
        currentPrice: 175.50,
        currency: 'USD',
        change: 2.25,
        changePercent: 1.30,
        lastUpdated: new Date(),
        icon: '🐄',
    },
    {
        id: '47',
        symbol: 'GF=F',
        name: 'Feeder Cattle',
        nameKo: '사육우',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.LIVESTOCK,
        currentPrice: 245.75,
        currency: 'USD',
        change: -3.50,
        changePercent: -1.40,
        lastUpdated: new Date(),
        icon: '🐄',
    },
    {
        id: '48',
        symbol: 'HE=F',
        name: 'Lean Hogs',
        nameKo: '돼지',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.LIVESTOCK,
        currentPrice: 78.90,
        currency: 'USD',
        change: 1.85,
        changePercent: 2.40,
        lastUpdated: new Date(),
        icon: '🐷',
    },
    // Agriculture - Dairy (유제품)
    {
        id: '49',
        symbol: 'DC=F',
        name: 'Milk',
        nameKo: '우유',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.DAIRY,
        currentPrice: 18.45,
        currency: 'USD',
        change: 0.35,
        changePercent: 1.93,
        lastUpdated: new Date(),
        icon: '🥛',
    },
    {
        id: '50',
        symbol: 'CSC=F',
        name: 'Cheese',
        nameKo: '치즈',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.DAIRY,
        currentPrice: 1.85,
        currency: 'USD',
        change: -0.05,
        changePercent: -2.63,
        lastUpdated: new Date(),
        icon: '🧀',
    },
    {
        id: '51',
        symbol: 'CB=F',
        name: 'Butter',
        nameKo: '버터',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.DAIRY,
        currentPrice: 2.95,
        currency: 'USD',
        change: 0.08,
        changePercent: 2.79,
        lastUpdated: new Date(),
        icon: '🧈',
    },
    // Agriculture - Other Specialty Crops (기타 특수 농산물)
    {
        id: '52',
        symbol: 'ADZUKI',
        name: 'Adzuki Beans',
        nameKo: '팥',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SPECIALTY,
        currentPrice: 12.75,
        currency: 'USD',
        change: 0.17,
        changePercent: 1.37,
        lastUpdated: new Date(),
        icon: '🫘',
    },
    {
        id: '53',
        symbol: 'PEANUTS',
        name: 'Peanuts',
        nameKo: '땅콩',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SPECIALTY,
        currentPrice: 625.50,
        currency: 'USD',
        change: -8.50,
        changePercent: -1.34,
        lastUpdated: new Date(),
        icon: '🥜',
    },
    {
        id: '54',
        symbol: 'ALMONDS',
        name: 'Almonds',
        nameKo: '아몬드',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SPECIALTY,
        currentPrice: 2.85,
        currency: 'USD',
        change: 0.12,
        changePercent: 4.40,
        lastUpdated: new Date(),
        icon: '🌰',
    },
    {
        id: '55',
        symbol: 'CASHEWS',
        name: 'Cashews',
        nameKo: '캐슈넛',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SPECIALTY,
        currentPrice: 4.25,
        currency: 'USD',
        change: -0.15,
        changePercent: -3.41,
        lastUpdated: new Date(),
        icon: '🌰',
    },
    {
        id: '56',
        symbol: 'WALNUTS',
        name: 'Walnuts',
        nameKo: '호두',
        category: CommodityCategory.AGRICULTURE,
        subcategory: AgriculturalSubcategory.SPECIALTY,
        currentPrice: 3.15,
        currency: 'USD',
        change: 0.08,
        changePercent: 2.61,
        lastUpdated: new Date(),
        icon: '🌰',
    },
    // Industrial Metals - Base Metals (전통 산업금속)
    {
        id: '57',
        symbol: 'HG=F',
        name: 'Copper',
        nameKo: '구리',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.BASE_METALS,
        currentPrice: 3.85,
        currency: 'USD',
        change: 0.05,
        changePercent: 1.32,
        lastUpdated: new Date(),
        icon: '🔶',
    },
    {
        id: '58',
        symbol: 'ALI=F',
        name: 'Aluminum',
        nameKo: '알루미늄',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.BASE_METALS,
        currentPrice: 2245.00,
        currency: 'USD',
        change: -15.50,
        changePercent: -0.69,
        lastUpdated: new Date(),
        icon: '⚙️',
    },
    {
        id: '59',
        symbol: 'NI=F',
        name: 'Nickel',
        nameKo: '니켈',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.BATTERY_ENERGY,
        currentPrice: 16850.00,
        currency: 'USD',
        change: 125.00,
        changePercent: 0.75,
        lastUpdated: new Date(),
        icon: '🔩',
    },
    // Industrial Metals - Rare & Strategic Metals (희소·전략 금속)
    {
        id: '60',
        symbol: 'MOLY',
        name: 'Molybdenum',
        nameKo: '몰리브덴',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 45.50,
        currency: 'USD',
        change: 1.25,
        changePercent: 2.82,
        lastUpdated: new Date(),
        icon: '⚛️',
    },
    {
        id: '61',
        symbol: 'TUNGSTEN',
        name: 'Tungsten',
        nameKo: '텅스텐',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 285.00,
        currency: 'USD',
        change: -5.50,
        changePercent: -1.89,
        lastUpdated: new Date(),
        icon: '⚛️',
    },
    {
        id: '62',
        symbol: 'VANADIUM',
        name: 'Vanadium',
        nameKo: '바나듐',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 28.75,
        currency: 'USD',
        change: 0.85,
        changePercent: 3.05,
        lastUpdated: new Date(),
        icon: '⚛️',
    },
    {
        id: '63',
        symbol: 'ANTIMONY',
        name: 'Antimony',
        nameKo: '안티모니',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 11.25,
        currency: 'USD',
        change: -0.35,
        changePercent: -3.02,
        lastUpdated: new Date(),
        icon: '⚛️',
    },
    {
        id: '64',
        symbol: 'BISMUTH',
        name: 'Bismuth',
        nameKo: '비스무트',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 8.95,
        currency: 'USD',
        change: 0.15,
        changePercent: 1.70,
        lastUpdated: new Date(),
        icon: '⚛️',
    },
    // Industrial Metals - Rare Earth Elements (희토류)
    {
        id: '65',
        symbol: 'ND',
        name: 'Neodymium',
        nameKo: '네오디뮴',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 125.50,
        currency: 'USD',
        change: 3.75,
        changePercent: 3.08,
        lastUpdated: new Date(),
        icon: '🔬',
    },
    {
        id: '66',
        symbol: 'PR',
        name: 'Praseodymium',
        nameKo: '프라세오디뮴',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 115.25,
        currency: 'USD',
        change: 2.50,
        changePercent: 2.22,
        lastUpdated: new Date(),
        icon: '🔬',
    },
    {
        id: '67',
        symbol: 'DY',
        name: 'Dysprosium',
        nameKo: '디스프로슘',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 385.00,
        currency: 'USD',
        change: -8.50,
        changePercent: -2.16,
        lastUpdated: new Date(),
        icon: '🔬',
    },
    {
        id: '68',
        symbol: 'TB',
        name: 'Terbium',
        nameKo: '테르븀',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 1250.00,
        currency: 'USD',
        change: 25.00,
        changePercent: 2.04,
        lastUpdated: new Date(),
        icon: '🔬',
    },
    {
        id: '69',
        symbol: 'LA',
        name: 'Lanthanum',
        nameKo: '란타넘',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 5.85,
        currency: 'USD',
        change: 0.12,
        changePercent: 2.09,
        lastUpdated: new Date(),
        icon: '🔬',
    },
    {
        id: '70',
        symbol: 'CE',
        name: 'Cerium',
        nameKo: '세륨',
        category: CommodityCategory.INDUSTRIAL_METALS,
        subcategory: IndustrialMetalsSubcategory.RARE_STRATEGIC,
        currentPrice: 4.25,
        currency: 'USD',
        change: -0.08,
        changePercent: -1.85,
        lastUpdated: new Date(),
        icon: '🔬',
    },
];

/**
 * Category labels in Korean
 */
export const CATEGORY_LABELS: Record<CommodityCategory, string> = {
    [CommodityCategory.PRECIOUS_METALS]: '귀금속',
    [CommodityCategory.ENERGY]: '에너지',
    [CommodityCategory.AGRICULTURE]: '농산물',
    [CommodityCategory.INDUSTRIAL_METALS]: '산업금속',
};

/**
 * Timeframe options for charts
 */
export const TIMEFRAME_OPTIONS = [
    { value: '1D', label: '1일' },
    { value: '1W', label: '1주' },
    { value: '1M', label: '1개월' },
    { value: '3M', label: '3개월' },
    { value: '1Y', label: '1년' },
    { value: 'ALL', label: '전체' },
] as const;
