import { Commodity, CommodityCategory } from '@/types';

/**
 * Mock commodity data for development
 */
export const MOCK_COMMODITIES: Commodity[] = [
    // Precious Metals
    {
        id: '1',
        symbol: 'XAUUSD',
        name: 'Gold',
        nameKo: '금',
        category: CommodityCategory.PRECIOUS_METALS,
        currentPrice: 2050.50,
        currency: 'USD',
        change: 15.25,
        changePercent: 0.75,
        lastUpdated: new Date(),
        icon: '🥇',
    },
    {
        id: '2',
        symbol: 'XAGUSD',
        name: 'Silver',
        nameKo: '은',
        category: CommodityCategory.PRECIOUS_METALS,
        currentPrice: 24.85,
        currency: 'USD',
        change: -0.35,
        changePercent: -1.39,
        lastUpdated: new Date(),
        icon: '🥈',
    },
    {
        id: '3',
        symbol: 'XPTUSD',
        name: 'Platinum',
        nameKo: '백금',
        category: CommodityCategory.PRECIOUS_METALS,
        currentPrice: 925.30,
        currency: 'USD',
        change: 8.50,
        changePercent: 0.93,
        lastUpdated: new Date(),
        icon: '⚪',
    },
    // Energy
    {
        id: '4',
        symbol: 'CL=F',
        name: 'Crude Oil WTI',
        nameKo: 'WTI 원유',
        category: CommodityCategory.ENERGY,
        currentPrice: 78.45,
        currency: 'USD',
        change: 2.15,
        changePercent: 2.82,
        lastUpdated: new Date(),
        icon: '🛢️',
    },
    {
        id: '5',
        symbol: 'BZ=F',
        name: 'Brent Crude',
        nameKo: '브렌트유',
        category: CommodityCategory.ENERGY,
        currentPrice: 82.30,
        currency: 'USD',
        change: 1.85,
        changePercent: 2.30,
        lastUpdated: new Date(),
        icon: '⛽',
    },
    {
        id: '6',
        symbol: 'NG=F',
        name: 'Natural Gas',
        nameKo: '천연가스',
        category: CommodityCategory.ENERGY,
        currentPrice: 2.85,
        currency: 'USD',
        change: -0.12,
        changePercent: -4.04,
        lastUpdated: new Date(),
        icon: '🔥',
    },
    // Agriculture - Grains (곡물)
    {
        id: '7',
        symbol: 'ZC=F',
        name: 'Corn',
        nameKo: '옥수수',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 485.25,
        currency: 'USD',
        change: 3.75,
        changePercent: 0.78,
        lastUpdated: new Date(),
        icon: '🌽',
    },
    {
        id: '8',
        symbol: 'ZW=F',
        name: 'Wheat',
        nameKo: '밀',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 625.50,
        currency: 'USD',
        change: -8.25,
        changePercent: -1.30,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    {
        id: '9',
        symbol: 'ZO=F',
        name: 'Oats',
        nameKo: '오트',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 385.75,
        currency: 'USD',
        change: 2.50,
        changePercent: 0.65,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    {
        id: '10',
        symbol: 'ZR=F',
        name: 'Rice',
        nameKo: '쌀',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 16.75,
        currency: 'USD',
        change: 0.25,
        changePercent: 1.52,
        lastUpdated: new Date(),
        icon: '🍚',
    },
    {
        id: '11',
        symbol: 'BARLEY',
        name: 'Barley',
        nameKo: '보리',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 245.30,
        currency: 'USD',
        change: -3.20,
        changePercent: -1.29,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    {
        id: '12',
        symbol: 'SORGHUM',
        name: 'Sorghum',
        nameKo: '수수',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 425.60,
        currency: 'USD',
        change: 5.40,
        changePercent: 1.28,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    // Agriculture - Oilseeds & Oils (유지종자 및 유지)
    {
        id: '13',
        symbol: 'ZS=F',
        name: 'Soybeans',
        nameKo: '대두',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 1425.50,
        currency: 'USD',
        change: -12.25,
        changePercent: -0.85,
        lastUpdated: new Date(),
        icon: '🫘',
    },
    {
        id: '14',
        symbol: 'ZM=F',
        name: 'Soybean Meal',
        nameKo: '대두박',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 425.80,
        currency: 'USD',
        change: 8.30,
        changePercent: 1.99,
        lastUpdated: new Date(),
        icon: '🫘',
    },
    {
        id: '15',
        symbol: 'ZL=F',
        name: 'Soybean Oil',
        nameKo: '대두유',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 52.45,
        currency: 'USD',
        change: -0.85,
        changePercent: -1.59,
        lastUpdated: new Date(),
        icon: '🫘',
    },
    {
        id: '16',
        symbol: 'RS=F',
        name: 'Canola',
        nameKo: '카놀라',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 585.20,
        currency: 'CAD',
        change: 12.50,
        changePercent: 2.18,
        lastUpdated: new Date(),
        icon: '🌻',
    },
    {
        id: '17',
        symbol: 'SUNFLOWER',
        name: 'Sunflower Seeds',
        nameKo: '해바라기씨',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 625.00,
        currency: 'USD',
        change: -5.75,
        changePercent: -0.91,
        lastUpdated: new Date(),
        icon: '🌻',
    },
    {
        id: '18',
        symbol: 'PALM',
        name: 'Palm Oil',
        nameKo: '팜유',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 4250.00,
        currency: 'MYR',
        change: 85.00,
        changePercent: 2.04,
        lastUpdated: new Date(),
        icon: '🌴',
    },
    // Agriculture - Soft Commodities (가공 식품/기호 농산물)
    {
        id: '19',
        symbol: 'KC=F',
        name: 'Coffee',
        nameKo: '커피',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 185.40,
        currency: 'USD',
        change: 4.20,
        changePercent: 2.32,
        lastUpdated: new Date(),
        icon: '☕',
    },
    {
        id: '20',
        symbol: 'SB=F',
        name: 'Sugar',
        nameKo: '설탕',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 24.35,
        currency: 'USD',
        change: 0.45,
        changePercent: 1.88,
        lastUpdated: new Date(),
        icon: '🍬',
    },
    {
        id: '21',
        symbol: 'CC=F',
        name: 'Cocoa',
        nameKo: '코코아',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 4250.00,
        currency: 'USD',
        change: 85.00,
        changePercent: 2.04,
        lastUpdated: new Date(),
        icon: '🍫',
    },
    {
        id: '22',
        symbol: 'OJ=F',
        name: 'Orange Juice',
        nameKo: '오렌지 주스',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 285.50,
        currency: 'USD',
        change: -5.25,
        changePercent: -1.81,
        lastUpdated: new Date(),
        icon: '🍊',
    },
    {
        id: '23',
        symbol: 'CT=F',
        name: 'Cotton',
        nameKo: '면화',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 82.15,
        currency: 'USD',
        change: -1.20,
        changePercent: -1.44,
        lastUpdated: new Date(),
        icon: '🌾',
    },
    // Agriculture - Livestock (축산물)
    {
        id: '24',
        symbol: 'LE=F',
        name: 'Live Cattle',
        nameKo: '생우',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 175.50,
        currency: 'USD',
        change: 2.25,
        changePercent: 1.30,
        lastUpdated: new Date(),
        icon: '🐄',
    },
    {
        id: '25',
        symbol: 'GF=F',
        name: 'Feeder Cattle',
        nameKo: '사육우',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 245.75,
        currency: 'USD',
        change: -3.50,
        changePercent: -1.40,
        lastUpdated: new Date(),
        icon: '🐄',
    },
    {
        id: '26',
        symbol: 'HE=F',
        name: 'Lean Hogs',
        nameKo: '돼지',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 78.90,
        currency: 'USD',
        change: 1.85,
        changePercent: 2.40,
        lastUpdated: new Date(),
        icon: '🐷',
    },
    // Agriculture - Dairy (유제품)
    {
        id: '27',
        symbol: 'DC=F',
        name: 'Milk',
        nameKo: '우유',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 18.45,
        currency: 'USD',
        change: 0.35,
        changePercent: 1.93,
        lastUpdated: new Date(),
        icon: '🥛',
    },
    {
        id: '28',
        symbol: 'CSC=F',
        name: 'Cheese',
        nameKo: '치즈',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 1.85,
        currency: 'USD',
        change: -0.05,
        changePercent: -2.63,
        lastUpdated: new Date(),
        icon: '🧀',
    },
    {
        id: '29',
        symbol: 'CB=F',
        name: 'Butter',
        nameKo: '버터',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 2.95,
        currency: 'USD',
        change: 0.08,
        changePercent: 2.79,
        lastUpdated: new Date(),
        icon: '🧈',
    },
    // Agriculture - Other Specialty Crops (기타 특수 농산물)
    {
        id: '30',
        symbol: 'ADZUKI',
        name: 'Adzuki Beans',
        nameKo: '팥',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 1850.00,
        currency: 'JPY',
        change: 25.00,
        changePercent: 1.37,
        lastUpdated: new Date(),
        icon: '🫘',
    },
    {
        id: '31',
        symbol: 'PEANUTS',
        name: 'Peanuts',
        nameKo: '땅콩',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 625.50,
        currency: 'USD',
        change: -8.50,
        changePercent: -1.34,
        lastUpdated: new Date(),
        icon: '🥜',
    },
    {
        id: '32',
        symbol: 'ALMONDS',
        name: 'Almonds',
        nameKo: '아몬드',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 2.85,
        currency: 'USD',
        change: 0.12,
        changePercent: 4.40,
        lastUpdated: new Date(),
        icon: '🌰',
    },
    {
        id: '33',
        symbol: 'CASHEWS',
        name: 'Cashews',
        nameKo: '캐슈넛',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 4.25,
        currency: 'USD',
        change: -0.15,
        changePercent: -3.41,
        lastUpdated: new Date(),
        icon: '🌰',
    },
    {
        id: '34',
        symbol: 'WALNUTS',
        name: 'Walnuts',
        nameKo: '호두',
        category: CommodityCategory.AGRICULTURE,
        currentPrice: 3.15,
        currency: 'USD',
        change: 0.08,
        changePercent: 2.61,
        lastUpdated: new Date(),
        icon: '🌰',
    },
    // Industrial Metals
    {
        id: '35',
        symbol: 'HG=F',
        name: 'Copper',
        nameKo: '구리',
        category: CommodityCategory.INDUSTRIAL_METALS,
        currentPrice: 3.85,
        currency: 'USD',
        change: 0.05,
        changePercent: 1.32,
        lastUpdated: new Date(),
        icon: '🔶',
    },
    {
        id: '36',
        symbol: 'ALI=F',
        name: 'Aluminum',
        nameKo: '알루미늄',
        category: CommodityCategory.INDUSTRIAL_METALS,
        currentPrice: 2245.00,
        currency: 'USD',
        change: -15.50,
        changePercent: -0.69,
        lastUpdated: new Date(),
        icon: '⚙️',
    },
    {
        id: '37',
        symbol: 'NI=F',
        name: 'Nickel',
        nameKo: '니켈',
        category: CommodityCategory.INDUSTRIAL_METALS,
        currentPrice: 16850.00,
        currency: 'USD',
        change: 125.00,
        changePercent: 0.75,
        lastUpdated: new Date(),
        icon: '🔩',
    },
];

/**
 * Category labels in Korean
 */
export const CATEGORY_LABELS: Record<CommodityCategory, string> = {
    [CommodityCategory.PRECIOUS_METALS]: '귀금속',
    [CommodityCategory.ENERGY]: '에너지',
    [CommodityCategory.AGRICULTURE]: '농산물',
    [CommodityCategory.INDUSTRIAL_METALS]: '산업금속',
};

/**
 * Timeframe options for charts
 */
export const TIMEFRAME_OPTIONS = [
    { value: '1D', label: '1일' },
    { value: '1W', label: '1주' },
    { value: '1M', label: '1개월' },
    { value: '3M', label: '3개월' },
    { value: '1Y', label: '1년' },
    { value: 'ALL', label: '전체' },
] as const;
